<link rel="stylesheet" href="res/css/templates_joomla/template.css" type="text/css">
<link rel="stylesheet" href="res/css/templates_joomla/joomla.css" type="text/css">
<link rel="stylesheet" href="res/css/templates_joomla/custom.css" type="text/css">
<link rel="stylesheet" href="res/css/templates_joomla/modules.css" type="text/css">
<link rel="stylesheet" href="res/css/templates_joomla/typography.css" type="text/css">
<link rel="stylesheet" href="res/css/templates_joomla/style1.css" type="text/css">
<link rel="stylesheet" href="res/css/templates_joomla/menu.css" type="text/css">
<script type="text/javascript" src="res/js/mootools-core.js" charset="UTF-8"></script>
<script type="text/javascript" src="res/js/mootools-more.js" charset="UTF-8"></script>
<script type="text/javascript" src="res/js/js_joomla/demo.js" charset="UTF-8"></script>